### ISSUE TITLE
[0.2.2-linux] Uncaught Exception

### ISSUE THREAD

**Issue by clstb** [jeperi/evelscan#2]
Distro: Arch

### Steps to reproduce
1. Download 0.2.2 linux binaries
2. chmod +x lscan
3. ./lscan

### Error report
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/home/claas/Downloads/0.2.2/evelscan-binary-linux64/resources/electron.asar/browser/init.js:121:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3

**Comment by jeperi** [comment]
Took a while, but the problem should now be fixed in the latest version.
